//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetDeCours.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class tacherResp
    {
        public int Id { get; set; }
        public int idper { get; set; }
        public string resp { get; set; }
    
        public virtual personne personne { get; set; }
        public virtual tache tache { get; set; }
    }
}
